var classList = [
    Assasin = {
        name: "Assasin",
        3: "+75% Crit Damage & 5% Crit Chance",
        4: "+75% Crit Damage & 5% Crit Chance",
        5: "+75% Crit Damage & 5% Crit Chance",
        6: "+150% Crit Damage & 20% Crit Chance",
        7: "+150% Crit Damage & 20% Crit Chance",
        8: "+150% Crit Damage & 20% Crit Chance",
        9: "+225% Crit Damage & 30% Crit Chance",
        value: 0,
    },

    Blademaster = {
        name: "Blademaster",
        3: "Blademasters have a 35% chance to strike 1 additional time each attack.",
        4: "Blademasters have a 35% chance to strike 1 additional time each attack.",
        5: "Blademasters have a 35% chance to strike 1 additional time each attack.",
        6: "Blademasters have a 35% chance to strike 2 additional times each attack.",
        7: "Blademasters have a 35% chance to strike 2 additional times each attack.",
        8: "Blademasters have a 35% chance to strike 2 additional times each attack.",
        9: "Blademasters have a 35% chance to strike 4 additional times each attack.",
        value: 0,
    },

    Brawler = {
        name: "Brawler",
        2: "Brawlers receive +250 bonus maximum health.",
        3: "Brawlers receive +250 bonus maximum health.",
        4: "Brawlers receive +500 bonus maximum health.",
        5: "Brawlers receive +500 bonus maximum health.",
        6: "Brawlers receive +900 bonus maximum health.",
        7: "Brawlers receive +900 bonus maximum health.",
        8: "Brawlers receive +900 bonus maximum health.",
        9: "Brawlers receive +900 bonus maximum health.",
        value: 0,
    },

    Elementalist = {
        name: "Elementalist",
        3: "Elementalists gain double mana from attacks. Also at the start of combat, summon a Golem with 2200 HP.",
        4: "Elementalists gain double mana from attacks. Also at the start of combat, summon a Golem with 2200 HP.",
        5: "Elementalists gain double mana from attacks. Also at the start of combat, summon a Golem with 2200 HP.",
        6: "Elementalists gain double mana from attacks. Also at the start of combat, summon a Golem with 2200 HP.",
        7: "Elementalists gain double mana from attacks. Also at the start of combat, summon a Golem with 2200 HP.",
        8: "Elementalists gain double mana from attacks. Also at the start of combat, summon a Golem with 2200 HP.",
        9: "Elementalists gain double mana from attacks. Also at the start of combat, summon a Golem with 2200 HP.",
        value: 0,
    },

    Guardian = {
        name: "Guardian",
        2: "At the start of combat, all adjacent allies receive +45 armor per stack. Guardians don't buff themselves.",
        3: "At the start of combat, all adjacent allies receive +45 armor per stack. Guardians don't buff themselves.",
        4: "At the start of combat, all adjacent allies receive +45 armor per stack. Guardians don't buff themselves.",
        5: "At the start of combat, all adjacent allies receive +45 armor per stack. Guardians don't buff themselves.",
        6: "At the start of combat, all adjacent allies receive +45 armor per stack. Guardians don't buff themselves.",
        7: "At the start of combat, all adjacent allies receive +45 armor per stack. Guardians don't buff themselves.",
        8: "At the start of combat, all adjacent allies receive +45 armor per stack. Guardians don't buff themselves.",
        9: "At the start of combat, all adjacent allies receive +45 armor per stack. Guardians don't buff themselves.",
        value: 0,
    },

    Gunslinger = {
        name: "Gunslinger",
        2: "After attacking, Gunslingers have a 50% chance to fire an additional attack that targets 1 other enemy",
        3: "After attacking, Gunslingers have a 50% chance to fire an additional attack that targets 1 other enemy",
        4: "After attacking, Gunslingers have a 50% chance to fire additional attacks that target 2 other enemies",
        5: "After attacking, Gunslingers have a 50% chance to fire additional attacks that target 2 other enemies",
        6: "After attacking, Gunslingers have a 50% chance to fire additional attacks that target 4 other enemies",
        7: "After attacking, Gunslingers have a 50% chance to fire additional attacks that target 4 other enemies",
        8: "After attacking, Gunslingers have a 50% chance to fire additional attacks that target 4 other enemies",
        9: "After attacking, Gunslingers have a 50% chance to fire additional attacks that target 4 other enemies",
        value: 0,
    },

    Knight = {
        name: "Knight",
        2: "All allies ignore 15 damage",
        3: "All allies ignore 15 damage",
        4: "All allies ignore 35 damage",
        5: "All allies ignore 35 damage",
        6: "All alies ignore 60 damage",
        7: "All alies ignore 60 damage",
        8: "All alies ignore 60 damage",
        9: "All alies ignore 60 damage",
        value: 0,
    },

    Ranger = {
        name: "Ranger",
        2: "Rangers have a 25% chance to double their attack speed for the next 3 seconds",
        3: "Rangers have a 25% chance to double their attack speed for the next 3 seconds",
        4: "Rangers have a 75% chance to double their attack speed fo the next 3 seconds",
        5: "Rangers have a 75% chance to double their attack speed fo the next 3 seconds",
        6: "Rangers have a 75% chance to double their attack speed fo the next 3 seconds",
        7: "Rangers have a 75% chance to double their attack speed fo the next 3 seconds",
        8: "Rangers have a 75% chance to double their attack speed fo the next 3 seconds",
        9: "Rangers have a 75% chance to double their attack speed fo the next 3 seconds",
        value: 0,
    },

    Shapeshifter = {
        name: "Shapeshifter",
        3: "Shapeshifters gain 60% bonus max health when they transform",
        4: "Shapeshifters gain 60% bonus max health when they transform",
        5: "Shapeshifters gain 60% bonus max health when they transform",
        6: "Shapeshifters gain 100% bonus max health when they transform",
        7: "Shapeshifters gain 100% bonus max health when they transform",
        8: "Shapeshifters gain 100% bonus max health when they transform",
        9: "Shapeshifters gain 100% bonus max health when they transform",
        value: 0,
    },

    Sorcerer = {
        name: "Sorcerer",
        3: "Sorcerers gain double mana from attacking and allies have 40% increased spell damage.",
        4: "Sorcerers gain double mana from attacking and allies have 40% increased spell damage.",
        5: "Sorcerers gain double mana from attacking and allies have 40% increased spell damage.",
        6: "Sorcerers gain double mana from attacking and allies have 100% increased spell damage.",
        7: "Sorcerers gain double mana from attacking and allies have 100% increased spell damage.",
        8: "Sorcerers gain double mana from attacking and allies have 100% increased spell damage.",
        9: "Sorcerers gain double mana from attacking and allies have 175% increased spell damage.",
        value: 0,
    }
]